global:
  scrape_interval: 15s

rule_files:
  - ops/alerts/recording_rules.yml
  - ops/alerts/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

